name: Bikebit
favicon: null
layout_spectrum: 0.3868891180027276
typography_spectrum: 0.7574792236555368
title: bike bit
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c4d51'
    - '#49786a'
    - '#040809'
    - '#6b9280'
    - '#f4f1eb'
  brandStrength: 0.48155270190909505
  lightness: 0.6131620933301747
  saturation: 0.3919555046595633
  rhythmicContrast: 0.31926434044726193
purpose: []
